// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVY0g49hFJ0wSfAZ_eQM6fjciVWO4-fb8',
    appId: '1:992540247722:web:d8ecb7deb854c19911b2d3',
    messagingSenderId: '992540247722',
    projectId: 'dynamicnotifications-2b375',
    authDomain: 'dynamicnotifications-2b375.firebaseapp.com',
    storageBucket: 'dynamicnotifications-2b375.firebasestorage.app',
    measurementId: 'G-KG6LB2Z1EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNGrUDr0QQQ2dFWpK0XVaF0zavhtxTdik',
    appId: '1:992540247722:android:b86660510fae3aaf11b2d3',
    messagingSenderId: '992540247722',
    projectId: 'dynamicnotifications-2b375',
    storageBucket: 'dynamicnotifications-2b375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDWcJS8SO6D0KXXwZXpZkOnLW8MGG7Lso',
    appId: '1:992540247722:ios:eb274c4a0f13738811b2d3',
    messagingSenderId: '992540247722',
    projectId: 'dynamicnotifications-2b375',
    storageBucket: 'dynamicnotifications-2b375.firebasestorage.app',
    iosBundleId: 'com.dynamicEmr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDWcJS8SO6D0KXXwZXpZkOnLW8MGG7Lso',
    appId: '1:992540247722:ios:e0d79124b1c5197e11b2d3',
    messagingSenderId: '992540247722',
    projectId: 'dynamicnotifications-2b375',
    storageBucket: 'dynamicnotifications-2b375.firebasestorage.app',
    iosBundleId: 'com.example.hrmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVY0g49hFJ0wSfAZ_eQM6fjciVWO4-fb8',
    appId: '1:992540247722:web:304a044bbcadfa9711b2d3',
    messagingSenderId: '992540247722',
    projectId: 'dynamicnotifications-2b375',
    authDomain: 'dynamicnotifications-2b375.firebaseapp.com',
    storageBucket: 'dynamicnotifications-2b375.firebasestorage.app',
    measurementId: 'G-1HNSGGSMG6',
  );

}