// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1f1Lrw2zq-YbKoygfbr3-AmOCSRC5qPw',
    appId: '1:773088288060:web:769f00608326a2ac659239',
    messagingSenderId: '773088288060',
    projectId: 'hrmnotifications-f9f90',
    authDomain: 'hrmnotifications-f9f90.firebaseapp.com',
    storageBucket: 'hrmnotifications-f9f90.firebasestorage.app',
    measurementId: 'G-WYZK4X1XPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTJdddbDOdLLpSUK-Km19beJdzaZ-w4x0',
    appId: '1:773088288060:android:0150906bd6274124659239',
    messagingSenderId: '773088288060',
    projectId: 'hrmnotifications-f9f90',
    storageBucket: 'hrmnotifications-f9f90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu_HTnDsYwmdWhiIa_dsZU82e3r49kEmw',
    appId: '1:773088288060:ios:e6bf114d65fb0a11659239',
    messagingSenderId: '773088288060',
    projectId: 'hrmnotifications-f9f90',
    storageBucket: 'hrmnotifications-f9f90.firebasestorage.app',
    iosBundleId: 'com.example.hrmsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu_HTnDsYwmdWhiIa_dsZU82e3r49kEmw',
    appId: '1:773088288060:ios:e6bf114d65fb0a11659239',
    messagingSenderId: '773088288060',
    projectId: 'hrmnotifications-f9f90',
    storageBucket: 'hrmnotifications-f9f90.firebasestorage.app',
    iosBundleId: 'com.example.hrmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1f1Lrw2zq-YbKoygfbr3-AmOCSRC5qPw',
    appId: '1:773088288060:web:9fe6cdf67d27f3c7659239',
    messagingSenderId: '773088288060',
    projectId: 'hrmnotifications-f9f90',
    authDomain: 'hrmnotifications-f9f90.firebaseapp.com',
    storageBucket: 'hrmnotifications-f9f90.firebasestorage.app',
    measurementId: 'G-S76Z4VXT4V',
  );
}
